channels:
  - conda-forge
dependencies:
  - r-base=4.0.0
  - r-abind
  - r-arrayhelpers
  - r-assertthat
  - r-backports
  - r-base64enc
  - r-bayesplot
  - r-bridgesampling
  - r-brms
  - r-Brobdingnag
  - r-broom
  - r-callr
  - r-cellranger
  - r-cli
  - r-cluster
  - r-coda
  - r-codetools
  - r-colorspace
  - r-colourpicker
  - r-crayon
  - r-crosstalk
  - r-data.table
  - r-DBI
  - r-dbplyr
  - r-digest
  - r-dplyr
  - r-DT
  - r-dygraphs
  - r-ellipsis
  - r-evaluate
  - r-extrafont
  - r-extrafontdb
  - r-fansi
  - r-fastmap
  - r-flextable
  - r-forcats
  - r-fs
  - r-future
  - r-future.apply
  - r-gdtools
  - r-generics
  - r-geometry
  - r-ggplot2
  - r-ggridges
  - r-ggstance
  - r-globals
  - r-glue
  - r-gridExtra
  - r-gtable
  - r-gtools
  - r-haven
  - r-hms
  - r-htmltools
  - r-htmlwidgets
  - r-httpuv
  - r-httr
  - r-igraph
  - r-inline
  - r-janitor
  - r-jsonlite
  - r-knitr
  - r-later
  - r-lattice
  - r-lifecycle
  - r-listenv
  - r-loo
  - r-lubridate
  - r-magic
  - r-magick
  - r-magrittr
  - r-markdown
  - r-Matrix
  - r-matrixStats
  - r-mime
  - r-miniUI
  - r-misc3d
  - r-modelr
  - r-munsell
  - r-mvtnorm
  - r-nlme
  - r-officer
  - r-packrat
  - r-pillar
  - r-pkgbuild
  - r-pkgconfig
  - r-plot3D
  - r-plyr
  - r-prettyunits
  - r-processx
  - r-progressr
  - r-promises
  - r-ps
  - r-purrr
  - r-R6
  - r-Rcpp
  - r-readr
  - r-readxl
  - r-reprex
  - r-reshape2
  - r-rlang
  - r-rmarkdown
  - r-rsconnect
  - r-rstan
  - r-rstantools
  - r-rstudioapi
  - r-Rttf2pt1
  - r-rvest
  - r-scales
  - r-sessioninfo
  - r-shiny
  - r-shinyjs
  - r-shinystan
  - r-shinythemes
  - r-snakecase
  - r-sp
  - r-StanHeaders
  - r-stringi
  - r-stringr
  - r-svUnit
  - r-systemfonts
  - r-threejs
  - r-tibble
  - r-tidybayes
  - r-tidyr
  - r-tidyselect
  - r-tidyverse
  - r-uuid
  - r-vctrs
  - r-withr
  - r-xfun
  - r-xml2
  - r-xtable
  - r-xts
  - r-zip
  - r-zoo
