channels:
  - conda-forge
dependencies:
  - r-base=4.0.2
  - r-tidyverse
  - r-brms
  - r-broom
  - r-colorspace
  - r-dplyr
  - r-extrafont
  - r-flextable
  - r-ggplot2
  - r-ggstance
  - r-magick
  - r-janitor
  - r-magrittr
  - r-modelr
  - r-readr
  - r-readxl
  - r-renv
  - r-reshape2
  - r-rstan
  - r-scales
  - r-stringr
  - r-tidybayes
  - r-tidyr
  
